#!/bin/sh
#
#  SBQ Daemon version 1.0
#  The SBQ's fake-daemon
#
#  Copyright 2014, Giovanni Nunes <giovanni.nunes@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
if [ -r ~/.sbqueuerc ]
then
	. ~/.sbqueuerc
	. $SBQDIR/sbqueue.conf
else
	echo "You need to set SBQDIR variable on .sbqueuerc file!"
	exit 1
fi

#
# Fixing a curious behavior with echo and older versions
#
ECHO='/bin/echo -e '

OLDPWD=`pwd`
MYPID=$$

#
# sbqDATETIME
#
sbqDATETIME()
{
	date +"%Y-%m-%d %X"
}

#
# sbqLOGGING
# To write a logs like a boss :)
#
sbqLOGGING()
{
	echo `date +"%Y-%m-%d %X"`" $*" >> $SBQLOG
}

if [ -z $SBQDIR ]
then
	echo "SBQDIR not defined!"
	exit 2
else
	#
	# is SBQD running?
	#
	if [ ! $SBQPID ]
	then
		echo "SBQD is running"
		exit 1
	else
		echo $MYPID > $SBQPID
		sbqLOGGING "Starting SBQD at PID $MYPID"
		
		while [ 1 ];
		do
			STAT=`cat $SBQSTA`
			
			#
			# is SBQD holded?
			#
			if [ "$STAT" = "RELEASED" ]
			then
				#
				# get the first task to run and...
				#
				TASK=`ls $SBQTSK/task-* 2>/dev/null | sort -n | head -n 1`
				
				if [ $TASK ]
				then
					TASK=`basename $TASK`
					#
					# ...runs! :-)
					#
					sbqLOGGING "processing $TASK"
					sh $SBQTSK/$TASK >$SBQOUT/$TASK.output 2>$SBQERR/$TASK.err
					rm -f $SBQTSK/$TASK > /dev/null
				fi
			fi
			#
			# wait a moment
			#
			sleep $SBQWAIT
		done
	fi
fi
